"use strict";
let firstName = "hari";
let age = 20;
let states = true;
let money;
let life = null;
let cat = "false";
console.log(firstName, age, states, money, life, cat);
console.log(typeof (cat));
let Age;
Age = 30;
console.log(Age);
let Name = 10;
let Names = ["next js", 40];
console.log(Names);
let arr = ["hello", 456, false];
console.log(arr);
let fn;
fn = false;
console.log(fn);
var list;
(function (list) {
    list[list["one"] = 3] = "one";
    list[list["two"] = 6] = "two";
    list[list["three"] = 1] = "three";
})(list || (list = {}));
console.log(list[1]);
