"use strict";
let firstName = "hari";
let age = 20;
let states = true;
let money;
let life = null;
let cat = "false";
console.log(firstName, age, states, money, life, cat);
console.log(typeof (cat));
let Age;
Age = 30;
console.log(Age);
let Name = 10;
